services:
  - type: web
    name: resumebuilder-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python server.py"
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
    rootDir: flask-server
